version: '3'
services:
  cinema_api:
    build: 
      context: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8001:8000"
    depends_on:
      - cinema_data
  cinema_data:
    image: 'postgres:14'
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${NAME_DB}
      POSTGRES_USER: ${USER_DB}
      POSTGRES_PASSWORD: ${PASSWORD_DB}
    volumes:
      - "cinema_db:/var/lib/postgresql/data"
volumes:
  cinema_db: